server:
  port: 8999
  servlet:
    context-path: /ehcachedemo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.176:3306/weixin_work?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ENC(uksJWR7h8OnBVxfw6fUUtUz77WQFzZPUhIH/0IR6fyV73pOrKHYwV4ZVxQdfVCXR)
